env.IMAGE_NAME = "ahmniab/eshop-ordering-api"
// VERSION = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()

stage('Run Tests for Ordering API') {
    sh """
    docker run --rm \
        -v "${WORKSPACE}/src/microservices/eShop.Ordering.API:/app:z" \
        -w /app \
        -e DOTNET_CLI_HOME=/app/.dotnet-temp \
        mcr.microsoft.com/dotnet/sdk:10.0 \
        dotnet test eShop.Ordering.API.sln
    """
}
stage('Build and Push Ordering API Image') {
    sh "docker build -t ${env.IMAGE_NAME}:${env.VERSION} src/microservices/eShop.Ordering.API"
    sh "docker push ${env.IMAGE_NAME}:${env.VERSION}"
}


stage('Deploy Ordering API to Kubernetes') {
    withKubeConfig([credentialsId: 'kubeconfig-credentials']) {
        sh "kubectl set image deployment/ordering-api-deployment ordering-api=${env.IMAGE_NAME}:${env.VERSION} --record"
        sh "kubectl rollout status deployment/ordering-api-deployment --timeout=120s"
    }
}
