pipeline {
    agent any

    environment {
        IMAGE_NAME = "ahmniab/eshop-catalog-api"
        // VERSION = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()

        DOCKERFILE_TEST = "Dockerfile.test"
        DOCKERFILE_APP = "Dockerfile"
        CONTEXT_PATH = "src/microservices/eShop.Catalog.API"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Test (via Docker)') {
            steps {
                sh "docker build -f ${DOCKERFILE_TEST} ${CONTEXT_PATH}"
            }
        }

        stage('Build Image') {
            steps {
                sh """
                    docker build \
                    -t ${IMAGE_NAME}:${VERSION} \
                    -f ${DOCKERFILE_APP} \
                    ${CONTEXT_PATH}
                """
            }
        }

        stage('Push to DockerHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh """
                        echo $PASS | docker login -u $USER --password-stdin
                        docker push ${IMAGE_NAME}:${VERSION}
                    """
                }
            }
        }
    }

    post {
        success {
            echo "Pipeline SUCCESS 🚀"
        }
        failure {
            echo "Pipeline FAILED ❌"
        }
    }
}
