apiVersion: v1
kind: Service
metadata:
  name: identity-api-service
spec:
  type: NodePort
  selector:
    app: identity-api
  ports:
    - protocol: TCP
      port: 5223
      targetPort: 5223
      nodePort: 30223
      name: http

